run: graph1.tex graph2.tex graph3.tex graph4.tex graph5.tex graph6.tex
	echo "done"
graph1.tex: graph1.py
	python graph1.py > graph1.tex
graph2.tex: graph2.py
	python graph2.py > graph2.tex
graph3.tex: graph3.py
	python graph3.py > graph3.tex
graph4.tex: graph4.py
	python graph4.py > graph4.tex
graph5.tex: graph5.py
	python graph5.py > graph5.tex

graph6.tex: graph6.py
	python graph6.py > graph6.tex
