nash robert:
	cp ../../../../assignment_tool/src/attributes.py .; cp ../../../../assignment_tool/src/makefile.py .; cp ../../../../assignment_tool/src/run.py .; cp ../../../../assignment_tool/src/file_structure.py .; cp ../../../../assignment_tool/src/latex_fragment.py .;

ryan:
	rm attributes.py; rm run.py; rm makefile.py; rm file_structure.py; rm latex_fragment.py
