copy:
	cp ../../../../assignment_tool/src/attributes.py .; cp ../../../../assignment_tool/src/makefile.py .; cp ../../../../assignment_tool/src/mk_assignment.py .; cp ../../../../assignment_tool/src/file_structure.py .; cp ../../../../assignment_tool/src/latex_fragment.py .; python mk_assignment.py; make clean

c clean:
	rm attributes.py; rm mk_assignment.py; rm makefile.py; rm file_structure.py; rm latex_fragment.py
